ALTER TABLE users ADD COLUMN age INT DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN telephone VARCHAR(20) DEFAULT NULL AFTER age;
ALTER TABLE users ADD COLUMN adresse TEXT DEFAULT NULL AFTER telephone;
ALTER TABLE users ADD COLUMN bio TEXT DEFAULT NULL AFTER adresse;
